// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHcUUyO-NqoQZnP0J39dA8wzvtQqSHHn0',
    appId: '1:1082929452728:web:1df3ab9ae9434096f7c64d',
    messagingSenderId: '1082929452728',
    projectId: 'social-app-e4c14',
    authDomain: 'social-app-e4c14.firebaseapp.com',
    storageBucket: 'social-app-e4c14.appspot.com',
    measurementId: 'G-KXCNB9XSCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx90F9knAr2GnKgRiSx9mX_uMZwhLYync',
    appId: '1:1082929452728:android:5cb412a6342e09a3f7c64d',
    messagingSenderId: '1082929452728',
    projectId: 'social-app-e4c14',
    storageBucket: 'social-app-e4c14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbnDPz7aXbTNBgsSmEjWaw90GynxtCMiY',
    appId: '1:1082929452728:ios:60e53f5ef11a0cfff7c64d',
    messagingSenderId: '1082929452728',
    projectId: 'social-app-e4c14',
    storageBucket: 'social-app-e4c14.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbnDPz7aXbTNBgsSmEjWaw90GynxtCMiY',
    appId: '1:1082929452728:ios:c1a3d6a578c3fc3af7c64d',
    messagingSenderId: '1082929452728',
    projectId: 'social-app-e4c14',
    storageBucket: 'social-app-e4c14.appspot.com',
    iosBundleId: 'com.example.social.RunnerTests',
  );
}
